### ISSUE TITLE
Docker update (:latest): SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by Aerya** [getferdi/server#86]
Hi,

I host Ferdi-server with Docker:
```
docker run -d \
--name=ferdiserver \
-e NODE_ENV=development \
-e DB_CONNECTION=sqlite \
-e DB_HOST=127.0.0.1 \
-e DB_PORT=3306 \
-e DB_USER=root \
-e DB_PASSWORD=xxx \
-e DB_DATABASE=xxx \
-e MAIL_CONNECTION=smtp \
-e SMPT_HOST=xxx \
-e SMTP_PORT=465 \
-e SSL=true \
-e MAIL_USERNAME=xxx \
-e MAIL_PASSWORD='xxx' \
-e MAIL_SENDER=xxx \
-e IS_CREATION_ENABLED=true \
-e IS_DASHBOARD_ENABLED=true \
-e IS_REGISTRATION_ENABLED=false \
-e CONNECT_WITH_FRANZ=true \
-p 1974:80 \
-v /home/aerya/docker/ferdiserver/config:/config \
-v /home/aerya/docker/ferdiserver/db:/app/database \
-v /home/aerya/docker/ferdiserver/recipes:/app/recipes \
--restart always \
getferdi/ferdi-server
```

I ran an update and got this error:
```
today at 18:16:49-------------------------------------
today at 18:16:49          ____           ___
today at 18:16:49         / __/__ _______/ (_)
today at 18:16:49        / _// -_) __/ _  / /
today at 18:16:49      _/_/  \__/_/  \_,_/_/
today at 18:16:49     / __/__ _____  _____ ____
today at 18:16:49    _\ \/ -_) __/ |/ / -_) __/
today at 18:16:49   /___/\__/_/  |___/\__/_/
today at 18:16:49Brought to you by getferdi.com
today at 18:16:49Support our Open Collective at:
today at 18:16:49https://opencollective.com/getferdi/
today at 18:16:49**** Generating Ferdi-server app key for first run ****
today at 18:16:50generated: unique APP_KEY
today at 18:16:50/entrypoint.sh: line 31: can't create /data/FERDI_APP_KEY.txt: nonexistent directory
today at 18:16:50**** App key is xxx. You can modify `/data/FERDI_APP_KEY.txt` to update the app key ****
today at 18:16:51Error: SQLITE_CANTOPEN: unable to open database file
today at 18:16:51    at Client_SQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/sqlite3/index.js:83:12)
today at 18:16:51    at create (/app/node_modules/knex/lib/client.js:280:23)
today at 18:16:51    at /app/node_modules/tarn/lib/Pool.js:315:34
today at 18:16:51    at Object.tryPromise (/app/node_modules/tarn/lib/utils.js:53:24)
today at 18:16:51    at /app/node_modules/tarn/lib/Pool.js:315:17
today at 18:16:51    at new Promise (<anonymous>)
today at 18:16:51    at callbackOrPromise (/app/node_modules/tarn/lib/Pool.js:306:12)
today at 18:16:51    at Pool._create (/app/node_modules/tarn/lib/Pool.js:236:9)
today at 18:16:51    at Pool._doCreate (/app/node_modules/tarn/lib/Pool.js:208:36)
today at 18:16:51    at Pool._tryAcquireOrCreate (/app/node_modules/tarn/lib/Pool.js:159:18)
today at 18:16:51    at Pool.acquire (/app/node_modules/tarn/lib/Pool.js:85:14)
today at 18:16:51    at /app/node_modules/knex/lib/client.js:335:26
today at 18:16:51From previous event:
today at 18:16:51    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:334:34)
today at 18:16:51    at Runner.ensureConnection (/app/node_modules/knex/lib/runner.js:228:24)
today at 18:16:51    at Runner.run (/app/node_modules/knex/lib/runner.js:34:42)
today at 18:16:51    at SchemaBuilder.Target.then (/app/node_modules/knex/lib/interface.js:20:43)
today at 18:16:51    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
today at 18:16:51  errno: 14,
today at 18:16:51  code: 'SQLITE_CANTOPEN'
today at 18:16:51}
today at 18:16:51chown: /data: No such file or directory
today at 18:18:46info: serving app on http://0.0.0.0:3333
```

**Comment by Aerya** [comment]
Ok.

You changed volumes.
https://github.com/getferdi/server/blob/master/docker/docker-compose.yml

Good joke.
I'm speachless.

**Comment by Aerya** [comment]
And port changed too.  Wow, what an exciting evening!  :)   Thanks
